### ISSUE TITLE
Error occurred while loading npc_cc120k.pt

### ISSUE THREAD

**Issue by heyuanpengpku** [ZhangXu0963/NPC#15]
Great work! However, I encountered the following error when trying to load `npc_cc120k.pt`. I have already ensured that the code can locate the corresponding weight file. Could the author please provide a solution or re-upload the pretrained model weights? Thank you very much!

```python
checkpoint = torch.load(args.resume)
Traceback (most recent call last):
  File "/home/hyp/Multi/NPC-master/main_NPC.py", line 209, in <module>
    main()
  File "/home/hyp/Multi/NPC-master/main_NPC.py", line 53, in main
    checkpoint = torch.load(args.resume)
  File "/home/hyp/miniconda3/envs/NPC/lib/python3.10/site-packages/torch/serialization.py", line 1072, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/hyp/miniconda3/envs/NPC/lib/python3.10/site-packages/torch/serialization.py", line 480, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

**Comment by ZhangXu0963** [comment]
Sorry for replying to you late. You can try to download the `npc_cc120k.pt` again and check if the path setting in `params.py` is correct. If the problem still exists, please send me your params setting and the error by email and I will help check it.
